var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(public)/reset-password/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1oojuil._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0alesp5._.js")
R.c("server/chunks/ssr/node_modules_next_dist_17i19if._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_128jj9t.js")
R.c("server/chunks/ssr/[root-of-the-server]__0h_bo4n._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1s8hecp._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_@opentelemetry_api_index_1oy1nwh.js")
R.c("server/chunks/ssr/[root-of-the-server]__185aj_9._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_(public)_reset-password_page_actions_0yc-z63.js")
R.m(448446)
module.exports=R.m(448446).exports
