var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/portal/pdf/[token]/[assessmentId]/route.js")
R.c("server/chunks/[root-of-the-server]__1of4fqt._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/[root-of-the-server]__1_hj7f4._.js")
R.c("server/chunks/[root-of-the-server]__0oxznu7._.js")
R.c("server/chunks/node_modules_next_dist_13kw1hb._.js")
R.c("server/chunks/_0wws22u._.js")
R.c("server/chunks/1oeh_server_app_api_portal_pdf_[token]_[assessmentId]_route_actions_11q7q4c.js")
R.m(692901)
module.exports=R.m(692901).exports
