// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/assessments" | "/assessments/[id]" | "/assessments/new" | "/athletes" | "/athletes/[id]" | "/athletes/[id]/edit" | "/athletes/new" | "/benchmarks" | "/compare" | "/dashboard" | "/forgot-password" | "/login" | "/onboarding/organization" | "/portal/[token]" | "/progress" | "/register" | "/reports" | "/reset-password" | "/schedule" | "/schedule/[id]/execute" | "/session-logs" | "/session-logs/[id]" | "/settings" | "/training-plans" | "/training-plans/[id]" | "/training-plans/exercises" | "/training-plans/new" | "/training-plans/templates"
type AppRouteHandlerRoutes = "/api/assessments/[id]/pdf" | "/api/auth/[...all]" | "/api/export/assessments" | "/api/export/athletes" | "/api/export/schedule" | "/api/export/session-logs" | "/api/portal/pdf/[token]/[assessmentId]"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/assessments/[id]/pdf": { "id": string; }
  "/api/auth/[...all]": { "all": string[]; }
  "/api/export/assessments": {}
  "/api/export/athletes": {}
  "/api/export/schedule": {}
  "/api/export/session-logs": {}
  "/api/portal/pdf/[token]/[assessmentId]": { "token": string; "assessmentId": string; }
  "/assessments": {}
  "/assessments/[id]": { "id": string; }
  "/assessments/new": {}
  "/athletes": {}
  "/athletes/[id]": { "id": string; }
  "/athletes/[id]/edit": { "id": string; }
  "/athletes/new": {}
  "/benchmarks": {}
  "/compare": {}
  "/dashboard": {}
  "/forgot-password": {}
  "/login": {}
  "/onboarding/organization": {}
  "/portal/[token]": { "token": string; }
  "/progress": {}
  "/register": {}
  "/reports": {}
  "/reset-password": {}
  "/schedule": {}
  "/schedule/[id]/execute": { "id": string; }
  "/session-logs": {}
  "/session-logs/[id]": { "id": string; }
  "/settings": {}
  "/training-plans": {}
  "/training-plans/[id]": { "id": string; }
  "/training-plans/exercises": {}
  "/training-plans/new": {}
  "/training-plans/templates": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
