// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(app)/assessments/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assessments/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/assessments/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/assessments/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assessments/new">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/assessments/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/assessments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assessments">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/assessments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/athletes/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/athletes/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/athletes/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/athletes/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/athletes/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/athletes/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/athletes/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/athletes/new">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/athletes/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/athletes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/athletes">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/athletes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/benchmarks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/benchmarks">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/benchmarks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/compare/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compare">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/compare/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/progress/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/progress">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/progress/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/schedule/[id]/execute/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/schedule/[id]/execute">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/schedule/[id]/execute/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/schedule">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/session-logs/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/session-logs/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/session-logs/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/session-logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/session-logs">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/session-logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/training-plans/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/training-plans/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/training-plans/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/training-plans/exercises/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/training-plans/exercises">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/training-plans/exercises/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/training-plans/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/training-plans/new">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/training-plans/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/training-plans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/training-plans">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/training-plans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/training-plans/templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/training-plans/templates">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/training-plans/templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/onboarding/organization/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding/organization">> = Specific
  const handler = {} as typeof import("../../src/app/onboarding/organization/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/portal/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/portal/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/assessments/[id]/pdf/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assessments/[id]/pdf">> = Specific
  const handler = {} as typeof import("../../src/app/api/assessments/[id]/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/[...all]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...all]">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/[...all]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/export/assessments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/export/assessments">> = Specific
  const handler = {} as typeof import("../../src/app/api/export/assessments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/export/athletes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/export/athletes">> = Specific
  const handler = {} as typeof import("../../src/app/api/export/athletes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/export/schedule/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/export/schedule">> = Specific
  const handler = {} as typeof import("../../src/app/api/export/schedule/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/export/session-logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/export/session-logs">> = Specific
  const handler = {} as typeof import("../../src/app/api/export/session-logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/portal/pdf/[token]/[assessmentId]/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portal/pdf/[token]/[assessmentId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/portal/pdf/[token]/[assessmentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(app)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
